In [1]:
import numpy as np
import pandas as pd

In [14]:
# Setup to create random data. The keys are people and the value is going to be a list of answers that the person gave.
NUMBER_OF_PEOPLE = 5
# Make a binomial distribution of survey answers. Do not really know if that would make a difference because i think the answer per question
# follows a binomial distribution and not the row of answers for one person.
people = {"".join([chr(np.random.randint(97,122)) for _ in range(10)]): np.random.binomial(n=5,p=0.5,size=20) for _ in range(NUMBER_OF_PEOPLE)}
people

{'cschcaklvq': array([0, 3, 2, 1, 4, 1, 3, 3, 1, 3, 2, 5, 0, 4, 3, 2, 1, 2, 1, 1]),
 'imttaqvxdo': array([5, 3, 2, 5, 1, 2, 4, 2, 2, 2, 3, 2, 3, 3, 2, 4, 3, 2, 3, 1]),
 'vyvpiygeru': array([2, 3, 1, 1, 4, 3, 2, 3, 3, 1, 4, 2, 1, 1, 3, 4, 4, 3, 2, 4]),
 'ireafrnrsl': array([2, 2, 1, 1, 2, 3, 1, 3, 2, 0, 4, 2, 3, 3, 3, 2, 5, 4, 2, 0]),
 'orudxggryu': array([1, 3, 2, 4, 4, 1, 2, 1, 1, 2, 2, 4, 3, 3, 1, 4, 3, 2, 4, 2])}

In [ ]:
similarity_matrix = np.zeros((NUMBER_OF_PEOPLE, NUMBER_OF_PEOPLE))
names = list(people.keys())
for i in range(len(names)- 1):
    person1 = people[names[i]]
    for j in range(i+1, len(names)):
        person2 = people[names[j]]
        similarity_matrix[i][j] = np.linalg.norm(person1 - person2)

# only really computes the upper right triangle because i,j is the same as j,i in terms of distance.
similarity_matrix

[0 3 2 1 4 1 3 3 1 3 2 5 0 4 3 2 1 2 1 1] [5 3 2 5 1 2 4 2 2 2 3 2 3 3 2 4 3 2 3 1]
[0 3 2 1 4 1 3 3 1 3 2 5 0 4 3 2 1 2 1 1] [2 3 1 1 4 3 2 3 3 1 4 2 1 1 3 4 4 3 2 4]
[0 3 2 1 4 1 3 3 1 3 2 5 0 4 3 2 1 2 1 1] [2 2 1 1 2 3 1 3 2 0 4 2 3 3 3 2 5 4 2 0]
[0 3 2 1 4 1 3 3 1 3 2 5 0 4 3 2 1 2 1 1] [1 3 2 4 4 1 2 1 1 2 2 4 3 3 1 4 3 2 4 2]
[5 3 2 5 1 2 4 2 2 2 3 2 3 3 2 4 3 2 3 1] [2 3 1 1 4 3 2 3 3 1 4 2 1 1 3 4 4 3 2 4]
[5 3 2 5 1 2 4 2 2 2 3 2 3 3 2 4 3 2 3 1] [2 2 1 1 2 3 1 3 2 0 4 2 3 3 3 2 5 4 2 0]
[5 3 2 5 1 2 4 2 2 2 3 2 3 3 2 4 3 2 3 1] [1 3 2 4 4 1 2 1 1 2 2 4 3 3 1 4 3 2 4 2]
[2 3 1 1 4 3 2 3 3 1 4 2 1 1 3 4 4 3 2 4] [2 2 1 1 2 3 1 3 2 0 4 2 3 3 3 2 5 4 2 0]
[2 3 1 1 4 3 2 3 3 1 4 2 1 1 3 4 4 3 2 4] [1 3 2 4 4 1 2 1 1 2 2 4 3 3 1 4 3 2 4 2]
[2 2 1 1 2 3 1 3 2 0 4 2 3 3 3 2 5 4 2 0] [1 3 2 4 4 1 2 1 1 2 2 4 3 3 1 4 3 2 4 2]


array([[0.        , 9.38083152, 8.06225775, 8.54400375, 7.        ],
       [0.        , 0.        , 8.06225775, 7.68114575, 6.40312424],
       [0.        , 0.        , 0.        , 6.164414  , 7.34846923],
       [0.        , 0.        , 0.        , 0.        , 7.87400787],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])